server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    elasticsearch:
      cluster-nodes: 116.62.38.97:9300
  redis:
    host: 116.62.38.97
    port: 63799
    password: root
mybatis:
  mapper-locations: classpath*:com/wzh/mapper/*Mapper.xml
  type-aliases-package: com.wzh.entity
logging:
  level:
    root: info
    com.wzh.dao: debug


